
//Sidebar
export const TOGGLE_SIDEBAR  = 'TOGGLE_SIDEBAR';

//Auth
export const USERNAME_CHANGED  = 'USERNAME_CHANGED';
export const PASSWORD_CHANGED   = 'PASSWORD_CHANGED';
export const LOGIN_SUCCESS   = 'LOGIN_SUCCESS';
export const LOGIN_FAIL   = 'LOGIN_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const START_SETUP_LOGIN = 'START_SETUP_LOGIN';
export const SETUP_LOGIN_SUCCESS = 'SETUP_LOGIN_SUCCESS';
export const SETUP_LOGIN_FAIL = 'SETUP_LOGIN_FAIL';



//Home
export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';
export const USER_INFO_UPDATE_FAIL = 'USER_INFO_UPDATE_FAIL';
export const MY_PROGRESS_UPDATE = 'MY_PROGRESS_UPDATE';
export const MY_PROGRESS_UPDATE_FAIL = 'MY_PROGRESS_UPDATE_FAIL';


//Admin
export const LATEST_PROJECTS_UPDATE = 'LATEST_PROJECTS_UPDATE';
export const LATEST_PROJECTS_UPDATE_FAIL = 'LATEST_PROJECTS_UPDATE_FAIL';

export const LATEST_TASKS_UPDATE = 'LATEST_TASKSS_UPDATE';
export const LATEST_TASKS_UPDATE_FAIL = 'LATEST_TASKS_UPDATE_FAIL';

export const LATEST_COMMENTS_UPDATE = 'LATEST_COMMENTS_UPDATE';
export const LATEST_COMMENTS_UPDATE_FAIL = 'LATEST_COMMENTS_UPDATE_FAIL';
export const ALL_USERS_UPDATE = 'ALL_USERS_UPDATE';
export const ALL_USERS_UPDATE_FAIL = 'ALL_USERS_UPDATE_FAIL';

//Project
export const SWITCH_HOME_BODY = 'SWITCH_ADMIN_HOME_BODY';
export const PROJECT_SAVE_START = 'PROJECT_SAVE_START';
export const PROJECT_SAVE_SUCCESS = 'PROJECT_SAVE_SUCCESS';
export const PROJECT_SAVE_FAIL = 'PROJECT_SAVE_FAIL';
export const PROJECT_NAME_CHANGED = 'PROJECT_NAME_CHANGED';
export const PROJECT_DESC_CHANGED = 'PROJECT_DESC_CHANGED';
export const PROJECT_NEW = 'PROJECT_NEW';
export const PROJECT_EDIT = 'PROJECT_EDIT';
export const PROJECT_MODAL_CANCEL = 'PROJECT_NEW_CANCEL';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DETAIL_START = 'PROJECT_DETAIL_START';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_DETAIL_FAIL = 'PROJECT_DETAIL_FAIL';
export const PROJECT_DETAIL_MODAL_CLOSE = 'PROJECT_DETAIL_MODAL_CLOSE';


//Projects 
export const ALL_PROJECTS_UPDATE_FAIL = 'ALL_PROJECTS_UPDATE_FAIL';
export const ALL_PROJECTS_UPDATE = 'ALL_PROJECTS_UPDATE';
export const PROJEC_TASK_ADDED = 'PROJEC_TASK_ADDED';
export const PROJEC_TASK_ADDED_FAIL = 'PROJEC_TASK_ADDED_FAIL';
export const PROJEC_TASK_CANCELED = 'PROJEC_TASK_CANCELED';
export const PROJEC_TASK_REMOVED = 'PROJEC_TASK_REMOVED';
export const TASK_USERS_CHANGED = 'TASK_USERS_CHANGED';
export const SELECT_PROJECT_UPDATE = 'SELECT_PROJECT_UPDATE';
export const SELECT_PROJECT_UPDATE_FAIL = 'SELECT_PROJECT_UPDATE_FAIL';


//Tasks
export const ALL_TASKS_UPDATE = 'ALL_TASKS_UPDATE';
export const ALL_TASKS_UPDATE_FAIL = 'ALL_TASKS_UPDATE_FAIL';
export const ALL_PROJECT_TASKS_UPDATE = 'ALL_PROJECT_TASKS_UPDATE';
export const ALL_PROJECT_TASKS_UPDATE_FAIL = 'ALL_PROJECT_TASKS_UPDATE_FAIL';

//Task
export const TASK_SAVE_START = 'TASK_SAVE_START';
export const TASK_SAVE_FAIL = 'TASK_SAVE_FAIL';
export const TASK_SAVE_SUCCESS = 'TASK_SAVE_SUCCESS';
export const TASK_TITLE_CHANGED = 'TASK_TITLE_CHANGED';
export const TASK_DESC_CHANGED = 'TASK_DESC_CHANGED';
export const TASK_NEW = 'TASK_NEW';
export const TASK_EDIT = 'TASK_EDIT';
export const TASK_MODAL_CANCEL = 'TASK_MODAL_CANCEL';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const SELECTED_TASK_USERS_UPDATE = 'SELECTED_TASK_USERS_UPDATE';
export const SELECTED_TASK_USERS_UPDATE_FAIL = 'SELECTED_TASK_USERS_UPDATE_FAIL';
export const SELECT_TASK_UPDATE = 'SELECT_TASK_UPDATE';
export const SELECT_TASK_UPDATE_FAIL = 'SELECT_TASK_UPDATE_FAIL';

//Comments
export const ALL_TASK_COMMENTS_UPDATE = 'ALL_TASK_COMMENTS_UPDATE';
export const ALL_TASK_COMMENTS_UPDATE_FAIL = 'ALL_TASK_COMMENTS_UPDATE_FAIL';
export const COMMENT_DELETE_FAIL = 'COMMENT_DELETE_FAIL';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_NEW = 'COMMENT_NEW';
export const COMMENT_TEXT_CHANGED = 'COMMENT_TEXT_CHANGED';
export const COMMENT_PROGRESS_CHANGED = 'COMMENT_PROGRESS_CHANGED';
export const COMMENT_MODAL_CANCEL = 'COMMENT_MODAL_CANCEL';
export const COMMENT_SAVE_FAIL = 'COMMENT_SAVE_FAIL';
export const COMMENT_SAVE_SUCCESS = 'COMMENT_SAVE_SUCCESS';


//My Project
export const MY_PROJECTS_UPDATE = 'MY_PROJECTS_UPDATE';
export const MY_PROJECTS_UPDATE_FAIL = 'MY_PROJECTS_UPDATE_FAIL';

//Mty Tasks
export const MY_TASKS_UPDATE = 'MY_TASKS_UPDATE';
export const MY_TASKS_UPDATE_FAIL = 'MY_TASKS_UPDATE_FAIL';


//User
export const USER_NEW = 'USER_NEW';
export const USER_EDIT = 'USER_EDIT';
export const RE_PASSWORD_CHANGED   = 'RE_PASSWORD_CHANGED';
export const FIRSTNAME_CHANGED = 'FIRSTNAME_CHANGED';
export const LASTNAME_CHANGED = 'LASTNAME_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const ENABLED_CHANGED = 'ENABLED_CHANGED';
export const USERROLE_CHANGED = 'USERROLE_CHANGED';
export const USER_MODAL_CANCEL = 'USER_MODAL_CANCEL';
export const USER_SAVE_SUCCESS = 'USER_SAVE_SUCCESS';
export const USER_SAVE_FAIL = 'USER_SAVE_FAIL';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const RESET_PWD_SUCCESS  = 'RESET_PWD_SUCCESS';
export const RESET_PWD_FAIL  = 'RESET_PWD_FAIL';
export const RESET_PWD  = 'RESET_PWD';
export const CANCEL_RESET_PWD  = 'CANCEL_RESET_PWD';
export const PROFILE_EDIT  = 'PROFILE_EDIT';
export const CANCEL_PROFILE_EDIT  = 'CANCEL_PROFILE_EDIT';
export const PROFILE_SAVE_FAIL  = 'PROFILE_SAVE_FAIL';
export const PROFILE_SAVE_SUCCESS  = 'PROFILE_SAVE_SUCCESS';
export const OLD_PASSWORD_CHANGED  = 'OLD_PASSWORD_CHANGED';
